server:
  port: 8082
  servlet:
    context-path: /api

account:
  config:
    database:
      schema: fc_account
    auth:
      url: http://localhost:8090
      client:
        id: account-service
        secret: account-secret

spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_core?currentSchema=${account.config.database.schema}
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        default_schema: ${account.config.database.schema}
        format_sql: true
    hibernate:
      ddl-auto: validate
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          customer-service:
            client_id: ${account.config.auth.client.id}
            client-secret: ${account.config.auth.client.secret}
            authorization-grant-type: client_credentials
            scopes: service.read,service.write,internal.api
            provider: auth-server
          transaction-service:
            client_id: ${account.config.auth.client.id}
            client_secret: ${account.config.auth.client.secret}
            authorization-grant-type: client_credentials
            scopes: service.read,service.write,internal.api
            provider: auth-server
        provider:
          auth-server:
            token-uri: ${account.config.auth.url}/oauth2/token
    user:
      name: financecore
      password: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
