server:
  port: 8082
  servlet:
    context-path: /api

account:
  config:
    database:
      schema: fc_account

spring:
  application:
    name: account
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_core?currentSchema=${account.config.database.schema}
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        default_schema: ${account.config.database.schema}
    hibernate:
      ddl-auto: validate
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
