server:
  port: 8090
  servlet:
    context-path: /api

auth:
  config:
    database:
      schema: fc_auth
    issuer:
      url: http://localhost:${server.port}

spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgres:http://localhost:5432/finance_core?currentSchema=${auth.config.database.schema}
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        default_schema: ${auth.config.database.schema}
    hibernate:
      ddl-auto: validate
  config:
    import: "optional:configserver:http://localhost:8888"

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
