server:
  port: 8080

gateway:
  config:
    auth:
      url: http://localhost:8090
      client:
        id: gateway-service
        secret: gateway-secret

spring:
  application:
    name: gateway
  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              lower-case-service-id: true
  security:
    user:
      name: fincancecore
      password: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: "*"