server:
  port: 8083
  servlet:
    context-path: /api

transaction:
  config:
    database:
      schema: fc_transaction
    auth:
      url: http://localhost:8090
      client:
        id: transaction-service
        secret: transaction-secret

spring:
  application:
    name: transaction
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_core?currentSchema=${transaction.config.database.schema}
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        default_schema: ${transaction.config.database.schema}
    hibernate:
      ddl-auto: validate
  security:
    oauth2:
      client:
        registration:
          account-service:
            client_id: ${transaction.config.auth.client.id}
            client_secret: ${transaction.config.auth.client.secret}
            authorization-grant-type: client_credentials
            scopes: service.read,service.write,internal.api
        provider:
          auth-server:
            token-uri: ${transaction.config.auth.url}/oauth2/token
    user:
      name: financecore
      password: password

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka