server:
  port: 8083
  servlet:
    context-path: /api

transaction:
  config:
    database:
      schema: fc_transaction

spring:
  application:
    name: transaction
  datasource:
    url: jdbc:postgresql://localhost:5432/finance_core?currentSchema=${transaction.config.database.schema}
    username: postgres
    password: password
  jpa:
    properties:
      hibernate:
        default_schema: ${transaction.config.database.schema}
    hibernate:
      ddl-auto: validate

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka